# Generated by Django 6.0.3 on 2026-07-28 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('requirements', models.TextField(blank=True, verbose_name='Exigences')),
                ('location', models.CharField(max_length=255, verbose_name='Lieu')),
                ('is_remote', models.BooleanField(default=False, verbose_name='Télétravail possible')),
                ('job_type', models.CharField(choices=[('full_time', 'Temps plein'), ('part_time', 'Temps partiel'), ('internship', 'Stage'), ('freelance', 'Freelance'), ('contract', 'CDD'), ('cdi', 'CDI')], max_length=20, verbose_name='Type')),
                ('experience_level', models.CharField(blank=True, choices=[('entry', 'Débutant'), ('junior', 'Junior (1-3 ans)'), ('mid', 'Confirmé (3-5 ans)'), ('senior', 'Senior (5+ ans)'), ('lead', 'Lead / Manager')], max_length=20, verbose_name="Niveau d'expérience")),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Salaire min (FCFA)')),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Salaire max (FCFA)')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Date limite')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Premium')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Vues')),
                ('applications_count', models.PositiveIntegerField(default=0, verbose_name='Candidatures')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='jobs.jobcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='companies.company')),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Lettre de motivation')),
                ('cv_file', models.FileField(blank=True, upload_to='applications/cvs/%Y/%m/', verbose_name='CV')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewed', 'Consultée'), ('shortlisted', 'Présélectionnée'), ('rejected', 'Rejetée'), ('hired', 'Recrutée')], default='pending', max_length=20, verbose_name='Statut')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.joboffer')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-applied_at'],
                'unique_together': {('candidate', 'job')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='jobs.joboffer')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'unique_together': {('user', 'job')},
            },
        ),
    ]
