# Generated by Django 6.0.3 on 2026-07-28 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('logo', models.ImageField(blank=True, upload_to='companies/logos/%Y/%m/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('email', models.EmailField(max_length=254, verbose_name='Email contact')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('location', models.CharField(max_length=255, verbose_name='Localisation')),
                ('industry', models.CharField(max_length=255, verbose_name="Secteur d'activité")),
                ('size', models.CharField(blank=True, choices=[('micro', '1-10'), ('small', '11-50'), ('medium', '51-250'), ('large', '251-1000'), ('enterprise', '1000+')], max_length=20, verbose_name='Taille')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année de fondation')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifiée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['-created_at'],
            },
        ),
    ]
