# Generated by Django 6.0.3 on 2026-07-28 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Localisation')),
                ('bio', models.TextField(blank=True, verbose_name='Bio')),
                ('cv_file', models.FileField(blank=True, upload_to='cvs/%Y/%m/', verbose_name='CV')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/', verbose_name='Photo')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='Compétences')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name="Années d'expérience")),
                ('education_level', models.CharField(blank=True, choices=[('none', 'Aucun'), ('cap', 'CAP/BEP'), ('bepc', 'BEPC'), ('bacc', 'Baccalauréat'), ('bts', 'BTS/DUT'), ('licence', 'Licence'), ('master', 'Master'), ('doctorat', 'Doctorat'), ('autre', 'Autre')], max_length=20, verbose_name="Niveau d'étude")),
                ('availability', models.BooleanField(default=True, verbose_name='Disponible')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Portfolio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil candidat',
                'verbose_name_plural': 'Profils candidats',
            },
        ),
    ]
