# Generated by Django 6.0.3 on 2026-08-08 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='jobs.jobapplication')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note recruteur',
                'verbose_name_plural': 'Notes recruteur',
                'ordering': ['-created_at'],
            },
        ),
    ]
